# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Madalyn Wright | Full Stack Developer
email: mwright8168@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio & Blog
baseurl: "/startbootstrap-freelancer-jekyll" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: maddix18
github_username:  madalynwright
facebook_username: maddi.wright
instagram_username: maddix18
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_url: https://www.linkedin.com/in/madalynwright


# Address information
address_street: 601 Tiffany Circle
address_city: Garner
address_state: NC
address_zip: 27606

# Build settings
markdown: kramdown
